name: Bug Report
description: Report a bug or issue with the Audemy platform
title: "[BUG]: "
labels: [bug]
body:
    - type: markdown
      attributes:
          value: |
              ## 🐞 Bug Reporting Guidelines
              Please follow this structured format to help us fix issues quickly. Make sure the bug is reproducible and hasn't already been reported.

    - type: input
      id: title
      attributes:
          label: Short bug title
          description: A clear, concise summary of the issue
          placeholder: "[Bug] Submit button unresponsive after second question in Addition Game"
      validations:
          required: true

    - type: textarea
      id: description
      attributes:
          label: Describe the bug
          description: What happened and what should have happened?
          placeholder: "After answering the second question in the Addition Game, the Submit button stops responding..."
      validations:
          required: true

    - type: textarea
      id: steps
      attributes:
          label: Steps to reproduce
          description: List the steps to reproduce the issue
          placeholder: |
              1. Go to the Game Zone
              2. Open the Addition Game
              3. Answer the first two questions
              4. Try clicking the "Submit" button on the third question
              5. Notice that nothing happens
      validations:
          required: true

    - type: textarea
      id: expected
      attributes:
          label: Expected behavior
          description: What should have happened?
          placeholder: "The Submit button should validate the answer, provide feedback, and move to the next question."
      validations:
          required: true

    - type: textarea
      id: actual
      attributes:
          label: Actual behavior
          description: What actually happened?
          placeholder: "The button appears clickable but does nothing and no feedback is shown."
      validations:
          required: true

    - type: textarea
      id: media
      attributes:
          label: Screenshots or recordings
          description: If applicable, drag and drop images or video clips that show the bug.
          placeholder: "Attach any relevant media files here."

    - type: textarea
      id: environment
      attributes:
          label: Environment details
          description: Add device, OS, and version information
          placeholder: |
              - Device: Desktop
              - OS: macOS Sonoma
              - Frontend Version: v0.3.4
              - Backend Version: main@6f9c2d1

    - type: textarea
      id: context
      attributes:
          label: Additional context
          description: Any other info (e.g., logged in or not, using a screen reader, keyboard-only navigation, frequency of bug)
          placeholder: "Happens every time; using VoiceOver on macOS; logged in as student"

    - type: checkboxes
      id: confirm
      attributes:
          label: Before submitting
          options:
              - label: I have searched for existing bug reports.
                required: true
              - label: I am using the latest version of Audemy.
                required: true
              - label: I can reliably reproduce this bug.
                required: true
