name: Feature Request
description: Suggest a new feature for Audemy
title: "[FEATURE]: "
labels: [feature]
body:
    - type: markdown
      attributes:
          value: "## 🎯 Feature Request\nUse this form to suggest a new feature you'd like to see in Audemy."

    - type: textarea
      id: description
      attributes:
          label: Describe the feature
          placeholder: "Clearly and concisely describe the feature."
      validations:
          required: true

    - type: textarea
      id: value
      attributes:
          label: Why is this feature important?
          placeholder: "Explain how this helps users or improves the product."
      validations:
          required: true

    - type: textarea
      id: solution
      attributes:
          label: Possible implementation
          placeholder: "Optional: any ideas on how to implement it?"

    - type: checkboxes
      id: confirm
      attributes:
          label: Before submitting
          options:
              - label: I have searched for existing feature requests.
                required: true
